networks:
  public:
    name: public
    driver: bridge
  
  private:
    name: private
    driver: bridge
    internal: true


services:
  server:
    extends:
      file: server/compose.yaml
      service: nginx
    networks:
      - public
      - private
  database:
    extends:
      file: database/compose.yaml
      service: postgres
    networks:
      - private
  adminer:
    extends:
      file: database/compose.yaml
      service: adminer
    networks:
      - private
    depends_on:
      database:
        condition: service_healthy
  cache:
    extends:
      file: cache/compose.yaml
      service: redis
    networks:
      - private
  messaging:
    extends:
      file: messaging/compose.yaml
      service: rabbitmq
    networks:
      - private
  storage:
    extends:
      file: storage/compose.yaml
      service: minio
    networks:
      - private
  auth:
    extends:
      file: auth/compose.yaml
      service: keycloak
    networks:
      - private
    depends_on:
      database:
        condition: service_healthy