services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start
    volumes:
      - ../server/config/certs/:/etc/x509/https/localhost
    environment:
      KC_HTTP_ENABLE: true
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/localhost/_wildcard.localhost.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/localhost/_wildcard.localhost-key.pem

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: auth.localhost
      KC_HTTPS_PORT: 443
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: false
      KC_HEALTH_ENABLED: false
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      JAVA_OPTS_APPEND: -Djava.net.preferIPv4Stack=true
    ports:
      - 443:443
      # - 9000:9000
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider https://auth.localhost/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5