services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/certs/:/etc/nginx/certs/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d/:/etc/nginx/conf.d/
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 10s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - action: sync+restart
          path: ./config
          target: /etc/nginx/