version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/certs/:/etc/nginx/certs/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d/:/etc/nginx/conf.d/