services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./config/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - action: sync+restart
          path: ./config
          target: /docker-entrypoint-initdb.d/
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 80:8080
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5